name: release
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}

permissions:
  contents: write

env:
  BIN: croner
  # If it's a tag, use the tag. Otherwise use a nightly-ish fallback.
  TAG: ${{ github.ref_type == 'tag' && github.ref_name || format('nightly-{0}', github.run_number) }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl tools (Linux only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Ensure packagers (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zip xz-utils

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip (non-Windows)
        if: runner.os != 'Windows'
        run: |
          B="target/${{ matrix.target }}/release/${{ env.BIN }}"
          command -v strip >/dev/null && strip "$B" || true

      - name: Package (tar.gz on macOS/Linux)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -e
          OUT=dist
          mkdir -p "$OUT"
          BIN_PATH="target/${{ matrix.target }}/release/${{ env.BIN }}"
          NAME="${{ env.BIN }}-${{ env.TAG }}-${{ matrix.target }}"
          tar -C "$(dirname "$BIN_PATH")" -czf "${OUT}/${NAME}.tar.gz" "$(basename "$BIN_PATH")"
          if command -v sha256sum >/dev/null; then
            sha256sum "${OUT}/${NAME}.tar.gz" > "${OUT}/${NAME}.tar.gz.sha256"
          else
            shasum -a 256 "${OUT}/${NAME}.tar.gz" | awk '{print $1}' > "${OUT}/${NAME}.tar.gz.sha256"
          fi

      - name: Package (zip on Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $out = "dist"
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          $bin = "target/${{ matrix.target }}/release/${{ env.BIN }}.exe"
          $name = "${{ env.BIN }}-${{ env.TAG }}-${{ matrix.target }}"
          Compress-Archive -Force -Path $bin -DestinationPath "$out\$name.zip"
          (Get-FileHash "$out\$name.zip" -Algorithm SHA256).Hash | Out-File "$out\$name.zip.sha256" -NoNewline

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
